### ISSUE TITLE
Should be able to identify refunded/cancelled orders from receipts API response with payment adjustment details

### ISSUE THREAD

**Issue by ravi18969** [etsy/open-api#496] opened 2022-05-31 04:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In our current requirement we need to fetch paid/refund/cancelled orders from Etsy store through V3 REST API. 
We are able to get paid orders from shop receipts as it has all the fields which are required for our mapping.

However we are not able to differentiate between normal orders and refunded orders through receipt details.
Due to which we are calling multiple APIs to first get ledger entries, then get payment adjustment details and based on that we are fetching receipt details.
Those ledger entries has payment adjustment details. We are considering those receipt id as refunded receipts. Which we feel isn’t the right way to get refunded order details.

While going through this approach we had to make these APIs call in a loop due to which we might end up reaching API limit per sec.

### Steps to reproduce

Call receipts endpoint and through response try to identity which one is refunded/cancelled orders.

### Expected behavior

Should be able to identify refunded/canceled order through receipts response.
Or there might be one endpoint which could get all the refunded orders with its payment adjustment details.

### Additional context

We need your help on identifying endpoint or maybe creating one new endpoint which could directly provide refunded/cancelled orders and its payment adjustment details.

**Comment by etsyachristensen** [comment] 2022-05-31 16:04
This is a duplicate of #302. Please track that issue. We are getting close to providing this data. I'll close this issue out to clean up the board.

**Closed by etsyachristensen** 2022-05-31 16:04 UTC
Labels: Bug
