### ISSUE TITLE
[BUG]: when_made value is returned as null for active listings

### ISSUE THREAD

**Issue by yovasx2** [etsy/open-api#453] opened 2022-04-25 23:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when_made is a required field to publish a listing, the API is returning that field as null

### Steps to reproduce

hit https://openapi.etsy.com/v3/application/listings/540708000?includes=Shipping
get the null value:
```
 "listing_id": 540708000,
    "user_id": 18437101,
    "shop_id": 6659792,
    ....
    "who_made": "collective",
    "when_made": null,
```

### Expected behavior

the when_made field must be different than null since this is mandatory in Etsy UI

### Additional context

<img width="1440" alt="Screen Shot 2022-04-25 at 18 28 11" src="https://user-images.githubusercontent.com/3578401/165191120-472ba52a-a795-48ba-a515-306569e0ca01.png">

**Comment by etsyachristensen** [comment] 2022-04-26 16:50
@yovasx2 I checked that listing id: 540708000. In our system there hasn't been an update via API on that listing for over 2 years. The last update has when_made input set to null.

Can you give me a listing id that's recent that is behaving this way?

**Comment by yovasx2** [comment] 2022-04-26 18:23
```
789057784
630753520
644816025
639349924
778089157
691760354
726960494
668507712
630990998
644581263
691600033
1206940358
735645349
608041423
605694391
1208215048
1208215912
744041692
659997044
867115379
```

**Comment by etsyachristensen** [comment] 2022-04-26 20:28
@yovasx2 I checked the listings. Here's what I found:

789057784 - invalid value: 2010_2021 
668507712 - invalid value: 2010_2021 
867115379 - invalid value: 2010_2021 

630753520 - invalid value: 2010_2020
644816025 - invalid value: 2010_2020
639349924 - invalid value: 2010_2020
778089157 - invalid value: 2010_2020
691760354 - invalid value: 2010_2020
726960494 - invalid value: 2010_2020
630990998 - invalid value: 2010_2020
644581263 - invalid value: 2010_2020
691600033 - invalid value: 2010_2020
659997044 - invalid value: 2010_2020

1208215048 - created using V2. No other API calls made on this listing
1208215912 - created using V2. No other API calls made on this listing

1206940358 - logged into user account and looks correct
735645349 - logged into user account and looks correct
608041423 - logged into user account and looks correct
605694391 - logged into user account and looks correct
744041692 - logged into user account and looks correct

All that said, I'm not really sure how those listings got invalid values. I don't immediately see that information in the API logs. So it could have been via another method.

**Comment by yovasx2** [comment] 2022-04-27 16:39
what does it mean `630990998 - invalid value: 2010_2020` and how do the customers have a null value in this field if this is mandatory?

**Comment by etsyachristensen** [comment] 2022-04-27 16:47
Well I'm not sure how the invalid date range was added to the system. I am bringing it to the fulfillment team to look into but the reason it's coming out `null` is because our system can't evaluate that invalid range value to a string to return. It is required to add a value for that field when creating a listing and technically in our database it's not null. It just returns as null because it can't match up. We will look into this but I can't say how soon we'll have a resolution to it.

**Comment by yovasx2** [comment] 2022-04-27 16:52
gotcha, when we take a look to the shop manager the when_made is displayed correctly but API is showing null, I can provide a longer list if needed

**Comment by etsyachristensen** [comment] 2022-04-27 18:39
Sure thing. I'll look at any you can send me.

**Comment by etsyachristensen** [comment] 2022-04-29 17:47
@yovasx2 We have deployed a fix for this issue. It should only return null when it's actually null or if the value (for some odd reason) is horribly formatted. We are working on implementing some protections against invalid values from being written, but this isn't coming through the OpenAPI so we are good there.

In the case where values are like the ones above, the safest approach is to return the decade value for the lowest decade in the string. So if the value in our db is `2010_2020` or `2010_2021`, what will output in the get requests is `2010_2019`. The data in the database is not getting changed, we are simply adjusting the value on-the-fly. This will allow your users to adjust the date range if necessary and then save, which hopefully will then send into Etsy the corrected value. Sort of a self-healing approach. 

We are also exploring options for correcting records that have invalid when_made values. But this may take some time to hammer out.

**Closed by etsyachristensen** 2022-04-29 17:47 UTC
Labels: Bug

**Comment by etsyachristensen** [comment] 2022-04-29 18:09
Oops. Spoke too soon. Caused a problem. Had to revert. will address and re-deploy hopefully today.

**Comment by etsyachristensen** [comment] 2022-05-02 16:51
@yovasx2 Ok this is now in production (sans errors). Please check it out.

**Comment by yovasx2** [comment] 2022-05-02 17:47
@etsyachristensen I don't get a clear understanding of the problem could u provide an example of what is going on and if I need to implement a data fix (which is gonna be complex because the values could be totally random depending on the product)

**Comment by etsyachristensen** [comment] 2022-05-02 18:00
Oh sorry about that. So what we found was that there were quite a few listings (many created via other apps) that had invalid date ranges, such as "2010-2020" or "2010-2021" just to name a couple. However, our system doesn't operate that way and the date range should have been either "2010-2019" or "2020-2022". This is why some listings were coming out of the OpenAPI as `null` for `when_made` when they should not have. So, what we did was to implement an on-the-fly correction of the date ranges. In order to most safely adjust for these bad ranges. We are taking the lower year in the range and adjusting the value to the range that matches that lower year. So for those two examples above, we are returning "2010-2019". This is not changing the values inside the database. It's simply modifying as the listings are requested via the OpenAPI. Our teams internally are looking into the cause of the bad ranges and how we can bulk-correct the ones with incorrect values. You should not need to make any changes on your end. We are just now not returning `null` unless the value is **actually** null in the database OR if the value is completely un-parsable (which is almost non-existent).

When your users view or edit their listings, the returned when_made value can be adjusted by the user if they don't agree with the adjustment we made and they can save their listing with the correct value.

The OpenAPI already validates the input for that field so your system is NOT passing incorrect values into the OpenAPI (because it would fail). You should be fine as-is.

**Comment by yovasx2** [comment] 2022-05-04 03:20
seems to be populating the majority of our listings, thanks!
