### ISSUE TITLE
[FEATURE]: hi, whether the views field in the product data will be added

### ISSUE THREAD

**Issue by penalty-zone** [etsy/open-api#571] opened 2022-08-22 09:58 UTC
### Is there an existing ticket for this?

- [X] I have searched the existing tickets

### Is your feature request related to a problem? Please describe

Using the v2 version to request product information can get the views field. I didn't find it in the v3 version, is there no?

### Describe the solution you'd like

I hope that in the v3 version, there is also a field of views in the product data obtained

### Describe any alternatives you've considered

NULL

### Additional context

NULL

**Comment by etsyachristensen** [comment] 2022-08-22 15:05
The `views` is currently not available in OpenAPI V3. We are looking at ways to restore this but there is no ETA. Closing this as it is a duplicate of #122

**Closed by etsyachristensen** 2022-08-22 15:05 UTC
Labels: Enhancement
