### ISSUE TITLE
[BUG]: Missing "edit" state in enum in OpenAPI definition

### ISSUE THREAD

**Issue by MaciejDerek** [etsy/open-api#556] opened 2022-08-11 08:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello,

I see the defect in he state enum in your open api definition. There are the following states: 
Enum: "active" "inactive" "sold_out" "draft" "expired"

However, after my product has been sold out it now has state = "edit" (this is what I receive in the response listing_id =1214842595. It is impossible to deserialize using open api definition.  

As per my understanding it should have automatically state = sold_out' or 'inactive' after quantity hits zero?

Please let me know if it's a known defect and if you will fix it shortly because it's a major defect for getting listings endpoint.

Regards,

### Steps to reproduce

1. Sell all products so that quantity of listings products go to zero
2. Call api endpoint https://openapi.etsy.com/v3/application/listings/{listing_id}

actual result: state of the listing = 'edit'

### Expected behavior

expected result: defined states are the following:
                            "enum": [
                                "active",
                                "inactive",
                                "sold_out",
                                "draft",
                                "expired"
                            ],

**Comment by etsyachristensen** [comment] 2022-08-11 14:14
We are aware. Closing this at it is a duplicate of #506. We already are working on documentation changes for this.

**Closed by etsyachristensen** 2022-08-11 14:14 UTC
Labels: Bug
