### ISSUE TITLE
[BUG]: getting image id 4066219216 is invalid when doing a put request to update inventory

### ISSUE THREAD

**Issue by KushGoyal** [etsy/open-api#601] opened 2022-09-23 14:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am trying to update inventory for a listing but I am getting an error for invalid image. The error should not come because there is no interaction with images for this request. It is an update inventory request.

Below are the request details:

url: `https://openapi.etsy.com/v3/application/v3/application/listings/<listing_id>/inventory`

method: PUT

response:

```json
 {"error":"image id 4066219216 is invalid"}
```

request body:
```json
{"price_on_property": [513], "quantity_on_property": [513], "sku_on_property": [513], "products": [{"sku": "<sku>", "offerings": [{"quantity": 108, "is_enabled": true, "price": 3.49}], "property_values": [{"property_id": 513, "values": ["1 Pack"], "scale_id": null, "value_ids": [102308126766], "property_name": "Multi Order"}]}, {"sku": "<sku>", "offerings": [{"quantity": 54, "is_enabled": true, "price": 6.49}], "property_values": [{"property_id": 513, "values": ["2 Pack"], "scale_id": null, "value_ids": [65191267311], "property_name": "Multi Order"}]}, {"sku": "<sku>", "offerings": [{"quantity": 36, "is_enabled": true, "price": 8.99}], "property_values": [{"property_id": 513, "values": ["3 Pack"], "scale_id": null, "value_ids": [52369518470], "property_name": "Multi Order"}]}]}
```

### Steps to reproduce

send put request to `https://openapi.etsy.com/v3/application/v3/application/listings/1219024668/inventory`

body:

```
{"price_on_property": [513], "quantity_on_property": [513], "sku_on_property": [513], "products": [{"sku": "ET-9465809597", "offerings": [{"quantity": 108, "is_enabled": true, "price": 3.49}], "property_values": [{"property_id": 513, "values": ["1 Pack"], "scale_id": null, "value_ids": [102308126766], "property_name": "Multi Order"}]}, {"sku": "ET-9465809603", "offerings": [{"quantity": 54, "is_enabled": true, "price": 6.49}], "property_values": [{"property_id": 513, "values": ["2 Pack"], "scale_id": null, "value_ids": [65191267311], "property_name": "Multi Order"}]}, {"sku": "ET-9724989372", "offerings": [{"quantity": 36, "is_enabled": true, "price": 8.99}], "property_values": [{"property_id": 513, "values": ["3 Pack"], "scale_id": null, "value_ids": [52369518470], "property_name": "Multi Order"}]}]}
```

### Expected behavior

the request should be successful

**Comment by etsyachristensen** [comment] 2022-09-23 14:55
This was caused by an issue that has been fixed in the past few days. You will need to run the updateVariationImages endpoint and pass in a valid image id for each variation that should have an image id. If it persists, the only solution is for the seller to log into their account and unlink the variation image that is causing the problem. We will work on a resolution to avoid the image id error being thrown on inventory, but in the meantime the above are your only solution options.

**Comment by etsyachristensen** [comment] 2022-09-23 20:31
@KushGoyal We have deployed a fix for this. You should not get that error any longer.

**Closed by etsyachristensen** 2022-09-23 20:31 UTC
Labels: Bug, OpenAPI
