### ISSUE TITLE
[FEATURE]: Direct Messages endpoints

### ISSUE THREAD

**Issue by caevv** [etsy/open-api#651] opened 2022-11-06 09:59 UTC
### Describe the solution you'd like

As I grow my shop I have been spending so much time dealing with customer services and not being able to work as much as I like on content creation and I know that I could be doing much better if I was able to do that.
My request is to please add support for direct message communications at the API.

**Comment by etsyachristensen** [comment] 2022-11-07 18:28
@caevv This is on our list of discussion topics. We have a number of issues open around messages. We'll close this ticket out as a duplicate of #171 .

**Closed by etsyachristensen** 2022-11-07 18:28 UTC
Labels: Resolution: Duplicate, Enhancement
