### ISSUE TITLE
[BUG]: Sending zero for item_width, item_length, item_height or item_weight results in a 500 server error

### ISSUE THREAD

**Issue by bitcrush-robin** [etsy/open-api#576] opened 2022-08-30 19:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Sending a unit string along with a zero for any of the dimensions results in a 500 error.

### Steps to reproduce

Create a new draft listing
Send a valid unit (item_weight_unit or item_dimensions_unit)
Send zero for one of the numeric values (item_width, item_length, item_height or item_weight)

### Expected behavior

A 401 or other message informing you that there's a problem with the input, or just accepting 0 as "unset".

**Comment by etsyachristensen** [comment] 2022-08-31 16:54
@bitcrush-robin Can you provide the full cURL post your system is making to our system so that I can debug this? I'm not able to reproduce the issue you are experiencing. If I pass in a zero for one of the numeric values I get a 400 error.
You can of course redact your api credentials before posting to the thread.

**Comment by bitcrush-robin** [comment] 2022-09-01 13:21
I've redacted IDs and tokens with [xxx]; item_length here is set to 0.  If you set it to 1 or another number, the request succeeds.

`curl -d "title=ZeroLengthTest&description=fsgfsg&price=16&taxonomy_id=1&quantity=999&who_made=someone_else&is_supply=true&when_made=made_to_order&processing_min=3&processing_max=5&shipping_profile_id=[xxx]&should_auto_renew=true&has_variations=true&tags=&is_personalizable=0&item_weight_unit=oz&item_weight=321&item_dimensions_unit=in&item_width=20&item_length=0&item_height=20" -H "x-api-key: [xxx]" -H "Authorization: Bearer [xxx]" -X POST https://openapi.etsy.com/v3/application/shops/[xxx]/listings`

Response, 500:
`{"error":"Server Error"}`

**Comment by etsyachristensen** [comment] 2022-09-06 14:10
Ok thank you @bitcrush-robin. I was able to duplicate it by using a manual (fixed price) shipping profile id. If I use a calculated shipping profile I get: `{"error":"This listing uses a calculated shipping profile. Length is required and must be greater than 0."}`

I'll work on making sure it returns a valid error response.

That said, if you are working with a manual type shipping profile you can omit the dimensions and weight without issue.

**Comment by etsyachristensen** [comment] 2022-09-07 21:04
@bitcrush-robin Ok so we just pushed a fix for this, but it isn't what you are wanting. According to the shipping internal team here, the rule is that if the shipping profile is calculated, all values must be there and be non-zero. If it's a fixed shipping profile, any value submitted must be non-zero or it will be null if not included in the dataset.

So, the fix is to now return a 400 error with a message rather than the 500 error that you should not have been getting.

Moving forward, if you have a zero value from a user, simply omit that dimensional property so that it doesn't throw the error or enforce a non-zero value rule.

**Closed by etsyachristensen** 2022-09-07 21:04 UTC
Labels: Bug
