### ISSUE TITLE
[BUG]: No order_id field in the response of getShopReceipt API

### ISSUE THREAD

**Issue by neelg-shapeways** [etsy/open-api#579] opened 2022-09-04 06:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Cannot find `order_id` field in the response of [getShopReceipt](https://developers.etsy.com/documentation/reference/#operation/getShopReceipt) API.

### Steps to reproduce

1. GET api call: https://openapi.etsy.com/v3/application/shops/{shop_id}/receipts/{receipt_id}
2. Response does not include `order_id` field

### Expected behavior

Like in API v2, [getShopReceipt](https://developers.etsy.com/documentation/reference/#operation/getShopReceipt) API should contain `order_id` (The numeric ID of the order this receipt is associated with)

**Comment by Gareth064** [comment] 2022-09-04 12:03
I thought a Receipt is the order. So the receiptId = orderId

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Neel Goswami ***@***.***>
Sent: Sunday, September 4, 2022 7:50:31 AM
To: etsy/open-api ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [etsy/open-api] [BUG]: No order_id field in the response of getShopReceipt API (Issue #579)


Is there an existing issue for this?

  *    I have searched the existing issues

Describe the bug

Cannot find order_id field in the response of getShopReceipt<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevelopers.etsy.com%2Fdocumentation%2Freference%2F%23operation%2FgetShopReceipt&data=05%7C01%7C%7C2bd9a542f94e4690c80908da8e41c2f1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637978710334042697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QwmkonCOZmLwNMPAQ6eETfQEdaeiD8iU72IEBmfCVC0%3D&reserved=0> API.

Steps to reproduce

  1.  GET api call: https://openapi.etsy.com/v3/application/shops/{shop_id}/receipts/{receipt_id}<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fopenapi.etsy.com%2Fv3%2Fapplication%2Fshops%2F%257Bshop_id%257D%2Freceipts%2F%257Breceipt_id%257D&data=05%7C01%7C%7C2bd9a542f94e4690c80908da8e41c2f1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637978710334042697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=y%2FbULxmGJs1HVKB2X0NCQSpWf5FsZSyMgSCzWqpBXUA%3D&reserved=0>
  2.  Response does not include order_id field

Expected behavior

Like in API v2, getShopReceipt<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevelopers.etsy.com%2Fdocumentation%2Freference%2F%23operation%2FgetShopReceipt&data=05%7C01%7C%7C2bd9a542f94e4690c80908da8e41c2f1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637978710334042697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QwmkonCOZmLwNMPAQ6eETfQEdaeiD8iU72IEBmfCVC0%3D&reserved=0> API should contain order_id (The numeric ID of the order this receipt is associated with)

Additional context

No response

**Comment by neelg-shapeways** [comment] 2022-09-04 20:41
I was also thinking the same but then why API v2 has both with different explanation?

![Screen Shot 2022-09-04 at 4 39 24 PM](https://user-images.githubusercontent.com/91752601/188332597-af6934a5-8683-4103-ad2f-ac4a6b90dbc6.png)

**Comment by etsyachristensen** [comment] 2022-09-06 15:39
In OpenAPI V3, we eliminated the order_id as it is a duplicate of the receipt_id object.

**Closed by etsyachristensen** 2022-09-06 15:39 UTC
Labels: Bug

**Comment by neelg-shapeways** [comment] 2022-09-06 15:43
Thank you @etsyachristensen for the confirmation.
