### ISSUE TITLE
[BUG] Letter case of state query parameter is not preserved in redirect url

### ISSUE THREAD

**Issue by dominicrathbone** [etsy/open-api#208] opened 2021-08-30 17:29 UTC
**Describe the bug**
When a mixed case state query parameter is used on the `/oauth/connect` page, the corresponding state query parameter in the redirect to the callback url is lower case. I am using passport-oauth2 which generates it's own mixed case state parameter and compares it with the one in the redirect url in a case-sensitive way, therefore failing the state check. I am not sure if the OAuth2 protocol indicates how this should be handled but I think it would be best practice to preserve the case.

**To Reproduce**

1. Provide a mixed-case state query parameter to the `https://www.etsy.com/oauth/connect` call.
2. Follow the normal user's OAuth flow until the redirect url is called.
3. Notice the state query parameter is now all lower case

**Expected behavior**
The case of the state query parameter is preserved.

**Additional context**
I am using the passport-oauth2 package which generates the value of the state parameter

**Comment by etsyachristensen** [comment] 2021-08-30 19:57
Closing this as it's essentially a duplicate of another issue we are tracking: https://github.com/etsy/open-api/issues/186

**Closed by etsyachristensen** 2021-08-30 19:58 UTC
Labels: Bug
