### ISSUE TITLE
[BUG]: updateListingInventory causes unexpected side effects to Variation Images

### ISSUE THREAD

**Issue by cal-tec** [etsy/open-api#384] opened 2022-02-28 22:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The [](https://developers.etsy.com/documentation/reference/#operation/updateListingInventory)updateListingInventory method causes unexpected side effects in relation to linked images on variations.

We have implemented a system for automatically updating inventory quantities and prices from our internal database. This process is made extremely complicated by the way the Etsy API v3 has been designed and is resource-intensive in relation to the number of API calls required for such a simple task. 
For a simple inventory update, every 100 listings on Etsy requires 201 calls to the Etsy API, this is not efficient but it seems to be the only way to use the V3 API to update inventory and we have it working and stable.
It should be noted that we used the [](https://developers.etsy.com/documentation/tutorials/listings#updating-inventory)documentation provided by Etsy as a framework for the process.

We were alerted to an issue yesterday that images linked to variations were becoming 'un-linked' when an inventory update was initiated. On further investigation, it appears that the inventory update deletes the associated ListingVariationImages. 
I can see that this is likely because an updateListingInventory call  re-generates the "property_values": ["value_ids": []]

I am currently working on a solution but it is yet again incredibly resource-intensive and to be quite honest not a sustainable solution to the problem for users with large amounts of listings.

Tee workaround solution seems to be to call getListingVariationImages prior to an inventory update, update the relevant id's form the inventory update response and then post the result to updateListingVariationImages.
I have not yet coded this but it seems that this may resolve the problem, all be it in a really resource-intensive way. Doing so would add a further 200 calls to an inventory update of 100 listings.

There are some optimizations that can be done where products do not have variations but in a situation where all products to be inventory updated have variations there would need to be 401 API calls per 100 listings. This seems utter madness.

Aside from the obvious issues of resource use the side effect of unlinking images is not highlighted in the documentation anywhere and is an unexpected side effect of an InvnetoryUpdate and is therefore a bug.

 

### Steps to reproduce

1. Call getlistingsByShop to get ListingId's and data
3. Call getListingInventory for a listing with variations and save result.
4. Call getListingVariationImages for the same listingId and save the result
5. Modify the getListingInventory result as documented in [](https://developers.etsy.com/documentation/tutorials/listings#updating-inventory) and update quantity and price as needed.
6. Call updateListingInventory with the modified data as a payload.
7. Call Call getListingVariationImages for the same listingId and compare the result to the previous getListingVariationImages call result.

### Expected behavior

Following the steps above the last getListingVariationImages will produce an empty result once an InventoryUpdate has been performed which is not the expected behavior.

### Additional context

As Etsy ventures into the wider world of e-commerce, the API needs to be both robust and user-friendly. The current design of the API is neither robust or user-friendly in relation to updating Inventory and needs to be reviewed urgently.

The problems seem to stem from the updateInventory method being in effect a PUT request and replacing the Inventory resource rather than updating it. This causes us to have to consistently call a get request before we can issue an update and this is not sustainable.

The idea that it takes n4+1 requests to update the quantities/prices per 100 listings is not efficient at all and our current plan is to have up to 300+ listings which would result in 1203 API calls per update. In our fast-moving business, we would like to update once per hour but this would not be possible with 1203 API calls as we would surpass the rate limit of 10,000 calls per day as it would require 28,872 API calls.

This is a real problem and seems to stem from poor API design rather than poor implementation.

**Comment by etsyachristensen** [comment] 2022-03-01 15:14
To address the variation images: The variation images should remain as long as the property_id isn't changed. The property is the variation type, for example Color. The values also must remain the same. So if you have 3 colors: red, green and blue, and then change green to gold, the variation image that was for green will be lost because that property id/value id combo on in the listing variations is no longer there. But if you kept red and blue, those variation images should remain.

As for the rest, I will let our product manager @nateswart address the concerns about robust and user friendly.

**Comment by nateswart** [comment] 2022-03-01 15:29
Hi @cal-tec  - thank you for your feedback and recommendations. We will take these into consideration as we plan future updates in our roadmap.

**Comment by cal-tec** [comment] 2022-03-02 11:41
> To address the variation images: The variation images should remain as long as the property_id isn't changed. The property is the variation type, for example Color. The values also must remain the same. So if you have 3 colors: red, green and blue, and then change green to gold, the variation image that was for green will be lost because that property id/value id combo on in the listing variations is no longer there. But if you kept red and blue, those variation images should remain.
> 
> As for the rest, I will let our product manager @nateswart address the concerns about robust and user friendly.

Can you please look into this issue again? It does not seem to be working as you describe above

As far as I can tell I am following the documented procedure found [here](https://developer.etsy.com/documentation/tutorials/listings#updating-inventory) for updating inventory from the API v3 Guide and also the section [here](https://developer.etsy.com/documentation/tutorials/listings#handling-variations-in-inventory-updates) on handling variations.

We are updating inventory by getting the inventory object from the API and then modifying it according to the above documentation and then posting it back to the updateListingInventory endpoint. I have checked the submitted object and the property_ids are not being changed and neither are any of the values. The result however is that variation images become unlinked.

On re-linking images in the backend of the website I chose random images for testing but on checking in the frontend Etsy website the original linked images are showing but they do not match the random ones chosen for testing. i.e The Linked image in the admin side of Etsy does not match what is being displayed in the front end Etsy site.

I repeated the process but this time made calls to getListingVariationImages before and after the inventory update and again after re-linking the images in the admin side of the Etsy website.
The results showed multiple linked images per variation which I did not think was possible.

I am 100% sure that the system is not performing as expected and that there is a valid bug in the system.

I would even go as far as to say that there are 3 different bugs but that they are likely caused by similar internal systems.

1. ListingVariationImages are becoming unlinked on API V3 InventoryUpdate
2. ListingVariationImages are not matching images chosen in Etsy Admin Website when unlinked by the above.
3. ListingVariationImages are allowing multiple images per variation option to be stored in the database.

Regards

cal-tec

**Comment by Josh-Newts** [comment] 2022-03-02 15:50
Hello,

Was this issue resolved? My dev team are currently building a stock system for our business to link our ERP and Etsy store and we are experiencing the same three bugs @cal-tec has documented. Despite following the documentation ListingVariationImages are becoming unlinked/disassociated on API V3 InventoryUpdate? We are following the example [here](https://developer.etsy.com/documentation/tutorials/listings/#handling-variations-in-inventory-updates) and using a free text field as the variation name. This is currently unusable as we can either have correct stock figures in our Etsy store or correct variant images but not both. We are trying to move a significant portion of our inventory onto Etsy from other channels but this is proving to be a major obstacle to using the Etsy marketplace.

Thanks,

**Comment by cal-tec** [comment] 2022-03-02 17:52
> I am looking into this now. It was fixed recently. I'll see if a reversion has taken place. Apologies for the misunderstanding.

Thanks for picking this up so fast. Hopefully, it will be a simple fix at your end.

**Comment by etsyachristensen** [comment] 2022-03-02 18:07
Ok so this is very interesting. In our production environment I setup a listing with 3 photos. I added a variation type with 3 variations. I assigned one photo to each variation. I saved the listing. I used the `getListingVariationImages` endpoint to confirm that there are 3 images assigned to the variations. I then used `getListingInventory` to pull down the current inventory. I removed the `is_deleted`, `product_id`, `offering_id`, `scale_name` and `listing` elements and changed the prices all to float values. The only change I made beyond that was to set the quantity and price to different values from what they were. I then submitted the inventory. I ran `getListingVariationImages` endpoint again and sure enough it zeroed out the images. So I edited the listing again to assign the 3 images (one to each variation). I confirmed with `getListingVariationImages` that the images were set. I then changed the inventory again to different values for quantity and price and submitted. Then I went back to `getListingVariationImages` and they didn't zero out... This is a head scratcher.

**Comment by etsyachristensen** [comment] 2022-03-02 18:23
Subsequent inventory updates seem to keep the variation images. I'm not sure why the first one clears. Still investigating.

**Comment by etsyachristensen** [comment] 2022-03-02 19:09
Yes. I just checked the test listing and I see the 3 variations. All three variations show a different image.

**Comment by cal-tec** [comment] 2022-03-04 00:18
@etsyachristensen Did you manage to make any progress on this? and is there an ETA on a bug fix?
As @Josh-Newts says "this is proving to be a major obstacle to using the Etsy marketplace"

**Comment by etsyachristensen** [comment] 2022-03-04 14:12
Yes as a matter of fact yesterday late in the day I posted what I think is a fix for this. Can you test it out with your app?

**Comment by cal-tec** [comment] 2022-03-04 14:49
Hi,
I have just done a quick test on a single listing and it looks like it has worked so far.
I will test this extensively over the weekend and get back to you with a final report.

It may also be helpful if @Josh-Newts can instruct his dev team to test this also as it sounds like they have a vast number of listings to process.

**Closed** 2022-03-07 23:20 UTC
Labels: Bug

**Comment by jeevan-dpl** [comment] 2022-04-06 11:11
I am also facing the very same problem. The variation images are getting unlinked. 
I tried fetching the variation image object before product update and tried to POST the same json and ended up with the error 
"error":"Could not update variation images because of the following error: variation with property_id 200 and value_id 566******* is invalid"

Any workaround??
